export const actionConstants = {
    ADD_GOAL: 'ADD_GOAL',
    DISCARD_GOAL_CREATION: 'DISCARD_GOAL_CREATION',
    TOGGLE_FILTERS: 'TOGGLE_FILTERS',
    CHANGE_GOAL_TITLE: 'CHANGE_GOAL_TITLE',
    CHANGE_GOAL_CATEGORY: 'CHANGE_GOAL_CATEGORY',
    CREATE_GOAL: 'CREATE_GOAL',
    CHANGE_VIEW: 'CHANGE_VIEW',
    CREATE_CATEGORY: 'CREATE_CATEGORY'
};